/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cars: Car;
    carBrands: CarBrand;
    carTypes: CarType;
    carsgallery: Carsgallery;
    rents: Rent;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cars: CarsSelect<false> | CarsSelect<true>;
    carBrands: CarBrandsSelect<false> | CarBrandsSelect<true>;
    carTypes: CarTypesSelect<false> | CarTypesSelect<true>;
    carsgallery: CarsgallerySelect<false> | CarsgallerySelect<true>;
    rents: RentsSelect<false> | RentsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    hero: Hero;
    review: Review;
    advantage: Advantage;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    review: ReviewSelect<false> | ReviewSelect<true>;
    advantage: AdvantageSelect<false> | AdvantageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: '1' | '2' | '3';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cars".
 */
export interface Car {
  id: number;
  title: string;
  plateNumber: string;
  carBrand?: (number | null) | CarBrand;
  carType?: (number | null) | CarType;
  carSpecification: {
    engine: number;
    passenger: number;
    transmission: 'manual' | 'at' | 'cvt' | 'dct' | 'amt';
    fuel: 'bensin' | 'solar' | 'listrik' | 'hybrid';
    color: string;
    odometer: number;
    registrationYear: number;
    buildYear: number;
  };
  gallery?:
    | {
        image: number | Carsgallery;
        tag?: ('exterior' | 'interior' | 'engine') | null;
        isPrimary?: boolean | null;
        isFeatured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  slug?: string | null;
  description: string;
  analytics: {
    status: 'available' | 'booked' | 'sold';
    purchasePrice: number;
    purchaseDate?: string | null;
    soldPrice?: number | null;
    repairs?:
      | {
          description: string;
          cost: number;
          id?: string | null;
        }[]
      | null;
    operationalCosts?:
      | {
          description: string;
          cost: number;
          id?: string | null;
        }[]
      | null;
    soldDate?: string | null;
  };
  price: number;
  financing: {
    downPaymentMin: number;
    leasing?:
      | {
          provider: string;
          interestRate: number;
          tenorMonths: ('12' | '24' | '36' | '48' | '60')[];
          id?: string | null;
        }[]
      | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carBrands".
 */
export interface CarBrand {
  id: number;
  title?: string | null;
  slug?: string | null;
  icon?: (number | null) | Media;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carTypes".
 */
export interface CarType {
  id: number;
  title?: string | null;
  slug?: string | null;
  icon?: (number | null) | Media;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carsgallery".
 */
export interface Carsgallery {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rents".
 */
export interface Rent {
  id: number;
  title: string;
  slug: string;
  carBrand?: (number | null) | CarBrand;
  carType?: (number | null) | CarType;
  rentalType?: ('lepas_kunci' | 'with_driver') | null;
  status: 'available' | 'rented' | 'service';
  pricing?: {
    daily?: number | null;
    weekly?: number | null;
    monthly?: number | null;
    yearly?: number | null;
  };
  availability?: {
    nextAvailableDate?: string | null;
    estimatedDays?: number | null;
  };
  bookings?:
    | {
        customerName?: string | null;
        startDate: string;
        endDate: string;
        status?: ('active' | 'completed' | 'cancelled') | null;
        id?: string | null;
      }[]
    | null;
  carSpecification: {
    engine: number;
    passenger?: number | null;
    transmission: 'manual' | 'at' | 'cvt' | 'dct' | 'amt';
    fuel: 'bensin' | 'solar' | 'listrik' | 'hybrid';
    color?: string | null;
    registrationYear?: number | null;
    buildYear?: number | null;
  };
  gallery?:
    | {
        image?: (number | null) | Carsgallery;
        tag?: ('exterior' | 'interior' | 'engine') | null;
        isFeatured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cars';
        value: number | Car;
      } | null)
    | ({
        relationTo: 'carBrands';
        value: number | CarBrand;
      } | null)
    | ({
        relationTo: 'carTypes';
        value: number | CarType;
      } | null)
    | ({
        relationTo: 'carsgallery';
        value: number | Carsgallery;
      } | null)
    | ({
        relationTo: 'rents';
        value: number | Rent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cars_select".
 */
export interface CarsSelect<T extends boolean = true> {
  title?: T;
  plateNumber?: T;
  carBrand?: T;
  carType?: T;
  carSpecification?:
    | T
    | {
        engine?: T;
        passenger?: T;
        transmission?: T;
        fuel?: T;
        color?: T;
        odometer?: T;
        registrationYear?: T;
        buildYear?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        tag?: T;
        isPrimary?: T;
        isFeatured?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  slug?: T;
  description?: T;
  analytics?:
    | T
    | {
        status?: T;
        purchasePrice?: T;
        purchaseDate?: T;
        soldPrice?: T;
        repairs?:
          | T
          | {
              description?: T;
              cost?: T;
              id?: T;
            };
        operationalCosts?:
          | T
          | {
              description?: T;
              cost?: T;
              id?: T;
            };
        soldDate?: T;
      };
  price?: T;
  financing?:
    | T
    | {
        downPaymentMin?: T;
        leasing?:
          | T
          | {
              provider?: T;
              interestRate?: T;
              tenorMonths?: T;
              id?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carBrands_select".
 */
export interface CarBrandsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carTypes_select".
 */
export interface CarTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carsgallery_select".
 */
export interface CarsgallerySelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rents_select".
 */
export interface RentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  carBrand?: T;
  carType?: T;
  rentalType?: T;
  status?: T;
  pricing?:
    | T
    | {
        daily?: T;
        weekly?: T;
        monthly?: T;
        yearly?: T;
      };
  availability?:
    | T
    | {
        nextAvailableDate?: T;
        estimatedDays?: T;
      };
  bookings?:
    | T
    | {
        customerName?: T;
        startDate?: T;
        endDate?: T;
        status?: T;
        id?: T;
      };
  carSpecification?:
    | T
    | {
        engine?: T;
        passenger?: T;
        transmission?: T;
        fuel?: T;
        color?: T;
        registrationYear?: T;
        buildYear?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        tag?: T;
        isFeatured?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  siteName: string;
  domain: string;
  logo: number | Media;
  location: string;
  address?: string | null;
  maps?: string | null;
  social?: {
    whatsapp?: string | null;
    instagram?: string | null;
    tiktok?: string | null;
    facebook?: string | null;
  };
  shortDescription?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
  };
  openGraph?: {
    ogTitle?: string | null;
    ogDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  business?: {
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    latitude?: string | null;
    longitude?: string | null;
  };
  advancedSEO?: {
    canonicalUrl?: string | null;
    robots?: ('index,follow' | 'noindex') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bagian hero di halaman utama
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  title: string;
  subTitle: string;
  /**
   * Pesan default untuk tombol WhatsApp
   */
  whatsappMessage: string;
  /**
   * 3 item keuntungan
   */
  advantages: {
    title: string;
    /**
     *
     *             Cara memilih icon:
     *             1. Buka https://phosphoricons.com
     *             2. Pilih tab "React"
     *             3. Cari icon yang diinginkan
     *             4. Copy nama icon (tanpa kata "Icon")
     *
     *             Contoh:
     *             <AddressBookTabsIcon /> → isi: AddressBookTabs
     *             <CarIcon /> → isi: Car
     *             <HeartIcon /> → isi: Heart
     *
     */
    icon: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bagian review di halaman utama
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review".
 */
export interface Review {
  id: number;
  title: string;
  subTitle: string;
  /**
   * Minimal 5 dan maksimal 30 review
   */
  reviews: {
    name: string;
    product: string;
    rating: '1' | '2' | '3' | '4' | '5';
    testimoni: string;
    avatar?: (number | null) | Media;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bagian advantages di halaman utama
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantage".
 */
export interface Advantage {
  id: number;
  title: string;
  subTitle: string;
  /**
   * Minimal 3 dan maksimal 9 keunggulan
   */
  advantages: {
    title: string;
    desc: string;
    /**
     *
     *             Cara memilih icon:
     *             1. Buka https://phosphoricons.com
     *             2. Pilih tab "React"
     *             3. Cari icon yang diinginkan
     *             4. Copy nama icon (tanpa kata "Icon")
     *
     *             Contoh:
     *             <AddressBookTabsIcon /> → isi: AddressBookTabs
     *             <CarIcon /> → isi: Car
     *             <HeartIcon /> → isi: Heart
     *
     */
    icon: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  siteName?: T;
  domain?: T;
  logo?: T;
  location?: T;
  address?: T;
  maps?: T;
  social?:
    | T
    | {
        whatsapp?: T;
        instagram?: T;
        tiktok?: T;
        facebook?: T;
      };
  shortDescription?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
      };
  openGraph?:
    | T
    | {
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
      };
  business?:
    | T
    | {
        city?: T;
        region?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  advancedSEO?:
    | T
    | {
        canonicalUrl?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  title?: T;
  subTitle?: T;
  whatsappMessage?: T;
  advantages?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review_select".
 */
export interface ReviewSelect<T extends boolean = true> {
  title?: T;
  subTitle?: T;
  reviews?:
    | T
    | {
        name?: T;
        product?: T;
        rating?: T;
        testimoni?: T;
        avatar?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advantage_select".
 */
export interface AdvantageSelect<T extends boolean = true> {
  title?: T;
  subTitle?: T;
  advantages?:
    | T
    | {
        title?: T;
        desc?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'cars'
      | 'carBrands'
      | 'carTypes'
      | 'carsgallery'
      | 'rents'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}