/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-sqlite'
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from '@payloadcms/db-sqlite/drizzle/sqlite-core'
import { sql, relations } from '@payloadcms/db-sqlite/drizzle'

export const users_sessions = sqliteTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    expiresAt: text('expires_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = sqliteTable(
  'users',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    role: text('role', { enum: ['1', '2', '3'] })
      .notNull()
      .default('3'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text('email').notNull(),
    resetPasswordToken: text('reset_password_token'),
    resetPasswordExpiration: text('reset_password_expiration').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text('salt'),
    hash: text('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: text('lock_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = sqliteTable(
  'media',
  {
    id: integer('id').primaryKey(),
    alt: text('alt'),
    imageOptimizer_thumbHash: text('image_optimizer_thumb_hash'),
    imageOptimizer_originalSize: numeric('image_optimizer_original_size', { mode: 'number' }),
    imageOptimizer_optimizedSize: numeric('image_optimizer_optimized_size', { mode: 'number' }),
    imageOptimizer_status: text('image_optimizer_status', { enum: ['complete', 'error'] }),
    imageOptimizer_error: text('image_optimizer_error'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: text('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: text('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: text('sizes_thumbnail_filename'),
    sizes_card_url: text('sizes_card_url'),
    sizes_card_width: numeric('sizes_card_width', { mode: 'number' }),
    sizes_card_height: numeric('sizes_card_height', { mode: 'number' }),
    sizes_card_mimeType: text('sizes_card_mime_type'),
    sizes_card_filesize: numeric('sizes_card_filesize', { mode: 'number' }),
    sizes_card_filename: text('sizes_card_filename'),
    sizes_large_url: text('sizes_large_url'),
    sizes_large_width: numeric('sizes_large_width', { mode: 'number' }),
    sizes_large_height: numeric('sizes_large_height', { mode: 'number' }),
    sizes_large_mimeType: text('sizes_large_mime_type'),
    sizes_large_filesize: numeric('sizes_large_filesize', { mode: 'number' }),
    sizes_large_filename: text('sizes_large_filename'),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
    index('media_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('media_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename),
    index('media_sizes_large_sizes_large_filename_idx').on(columns.sizes_large_filename),
  ],
)

export const cars_gallery = sqliteTable(
  'cars_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => carsgallery.id, {
        onDelete: 'set null',
      }),
    tag: text('tag', { enum: ['exterior', 'interior', 'engine'] }).notNull(),
    isSlideshow: integer('is_slideshow', { mode: 'boolean' }),
  },
  (columns) => [
    index('cars_gallery_order_idx').on(columns._order),
    index('cars_gallery_parent_id_idx').on(columns._parentID),
    index('cars_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cars.id],
      name: 'cars_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cars_features = sqliteTable(
  'cars_features',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    feature: text('feature'),
  },
  (columns) => [
    index('cars_features_order_idx').on(columns._order),
    index('cars_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cars.id],
      name: 'cars_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cars_analytics_repairs = sqliteTable(
  'cars_analytics_repairs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    description: text('description').notNull(),
    cost: numeric('cost', { mode: 'number' }).notNull().default(0),
  },
  (columns) => [
    index('cars_analytics_repairs_order_idx').on(columns._order),
    index('cars_analytics_repairs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cars.id],
      name: 'cars_analytics_repairs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cars_analytics_operational_costs = sqliteTable(
  'cars_analytics_operational_costs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    description: text('description').notNull(),
    cost: numeric('cost', { mode: 'number' }).notNull().default(0),
  },
  (columns) => [
    index('cars_analytics_operational_costs_order_idx').on(columns._order),
    index('cars_analytics_operational_costs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cars.id],
      name: 'cars_analytics_operational_costs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cars_financing_leasing_tenor_months = sqliteTable(
  'cars_financing_leasing_tenor_months',
  {
    order: integer('order').notNull(),
    parent: text('parent_id').notNull(),
    value: text('value', { enum: ['11', '23', '35', '47', '59', '71', '83', '95', '119'] }),
    id: integer('id').primaryKey(),
  },
  (columns) => [
    index('cars_financing_leasing_tenor_months_order_idx').on(columns.order),
    index('cars_financing_leasing_tenor_months_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [cars_financing_leasing.id],
      name: 'cars_financing_leasing_tenor_months_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const cars_financing_leasing = sqliteTable(
  'cars_financing_leasing',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    provider: text('provider').notNull(),
    interestRate: numeric('interest_rate', { mode: 'number' }).notNull(),
  },
  (columns) => [
    index('cars_financing_leasing_order_idx').on(columns._order),
    index('cars_financing_leasing_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cars.id],
      name: 'cars_financing_leasing_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const cars = sqliteTable(
  'cars',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    carBrand: integer('car_brand_id')
      .notNull()
      .references(() => car_brands.id, {
        onDelete: 'set null',
      }),
    carType: integer('car_type_id')
      .notNull()
      .references(() => car_types.id, {
        onDelete: 'set null',
      }),
    carSpecification_engine: numeric('car_specification_engine', { mode: 'number' }).notNull(),
    carSpecification_passenger: numeric('car_specification_passenger', { mode: 'number' })
      .notNull()
      .default(5),
    carSpecification_transmission: text('car_specification_transmission', {
      enum: ['manual', 'at', 'cvt', 'dct', 'amt'],
    })
      .notNull()
      .default('manual'),
    carSpecification_fuel: text('car_specification_fuel', {
      enum: ['bensin', 'solar', 'listrik', 'hybrid'],
    })
      .notNull()
      .default('bensin'),
    carSpecification_color: text('car_specification_color').notNull(),
    carSpecification_odometer: numeric('car_specification_odometer', { mode: 'number' }).notNull(),
    carSpecification_registrationYear: numeric('car_specification_registration_year', {
      mode: 'number',
    }).notNull(),
    carSpecification_buildYear: numeric('car_specification_build_year', {
      mode: 'number',
    }).notNull(),
    cardthumbnail: integer('cardthumbnail_id')
      .notNull()
      .references(() => carsgallery.id, {
        onDelete: 'set null',
      }),
    slug: text('slug'),
    description: text('description').notNull(),
    analytics_status: text('analytics_status', { enum: ['available', 'booked', 'sold'] })
      .notNull()
      .default('available'),
    analytics_purchasePrice: numeric('analytics_purchase_price', { mode: 'number' })
      .notNull()
      .default(0),
    analytics_purchaseDate: text('analytics_purchase_date')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    analytics_soldPrice: numeric('analytics_sold_price', { mode: 'number' }).default(0),
    analytics_soldDate: text('analytics_sold_date').default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    analytics_ownership_ownershipType: text('analytics_ownership_ownership_type', {
      enum: ['dealer', 'personal'],
    })
      .notNull()
      .default('dealer'),
    analytics_ownership_personalOwner_name: text(
      'analytics_ownership_personal_owner_name',
    ).notNull(),
    analytics_ownership_personalOwner_phone: text(
      'analytics_ownership_personal_owner_phone',
    ).notNull(),
    analytics_ownership_personalOwner_nik: text('analytics_ownership_personal_owner_nik').notNull(),
    analytics_ownership_personalOwner_address: text(
      'analytics_ownership_personal_owner_address',
    ).notNull(),
    analytics_ownership_stnkName: text('analytics_ownership_stnk_name').notNull(),
    analytics_ownership_plateNumber: text('analytics_ownership_plate_number').notNull(),
    analytics_ownership_handOwnership: numeric('analytics_ownership_hand_ownership', {
      mode: 'number',
    })
      .notNull()
      .default(1),
    price: numeric('price', { mode: 'number' }).notNull(),
    financing_downPaymentMin: numeric('financing_down_payment_min', { mode: 'number' }).notNull(),
    meta_title: text('meta_title'),
    meta_description: text('meta_description'),
    meta_image: integer('meta_image_id').references(() => carsgallery.id, {
      onDelete: 'set null',
    }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text('deleted_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('cars_car_brand_idx').on(columns.carBrand),
    index('cars_car_type_idx').on(columns.carType),
    index('cars_cardthumbnail_idx').on(columns.cardthumbnail),
    uniqueIndex('cars_slug_idx').on(columns.slug),
    index('cars_meta_meta_image_idx').on(columns.meta_image),
    index('cars_updated_at_idx').on(columns.updatedAt),
    index('cars_created_at_idx').on(columns.createdAt),
    index('cars_deleted_at_idx').on(columns.deletedAt),
  ],
)

export const car_brands = sqliteTable(
  'car_brands',
  {
    id: integer('id').primaryKey(),
    title: text('title'),
    slug: text('slug'),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    count: numeric('count', { mode: 'number' }).default(0),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('car_brands_title_idx').on(columns.title),
    uniqueIndex('car_brands_slug_idx').on(columns.slug),
    index('car_brands_icon_idx').on(columns.icon),
    index('car_brands_updated_at_idx').on(columns.updatedAt),
    index('car_brands_created_at_idx').on(columns.createdAt),
  ],
)

export const car_types = sqliteTable(
  'car_types',
  {
    id: integer('id').primaryKey(),
    title: text('title'),
    slug: text('slug'),
    icon: integer('icon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    count: numeric('count', { mode: 'number' }).default(0),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex('car_types_title_idx').on(columns.title),
    uniqueIndex('car_types_slug_idx').on(columns.slug),
    index('car_types_icon_idx').on(columns.icon),
    index('car_types_updated_at_idx').on(columns.updatedAt),
    index('car_types_created_at_idx').on(columns.createdAt),
  ],
)

export const carsgallery = sqliteTable(
  'carsgallery',
  {
    id: integer('id').primaryKey(),
    alt: text('alt'),
    imageOptimizer_thumbHash: text('image_optimizer_thumb_hash'),
    imageOptimizer_originalSize: numeric('image_optimizer_original_size', { mode: 'number' }),
    imageOptimizer_optimizedSize: numeric('image_optimizer_optimized_size', { mode: 'number' }),
    imageOptimizer_status: text('image_optimizer_status', { enum: ['complete', 'error'] }),
    imageOptimizer_error: text('image_optimizer_error'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
    sizes_thumbnail_url: text('sizes_thumbnail_url'),
    sizes_thumbnail_width: numeric('sizes_thumbnail_width', { mode: 'number' }),
    sizes_thumbnail_height: numeric('sizes_thumbnail_height', { mode: 'number' }),
    sizes_thumbnail_mimeType: text('sizes_thumbnail_mime_type'),
    sizes_thumbnail_filesize: numeric('sizes_thumbnail_filesize', { mode: 'number' }),
    sizes_thumbnail_filename: text('sizes_thumbnail_filename'),
    sizes_card_url: text('sizes_card_url'),
    sizes_card_width: numeric('sizes_card_width', { mode: 'number' }),
    sizes_card_height: numeric('sizes_card_height', { mode: 'number' }),
    sizes_card_mimeType: text('sizes_card_mime_type'),
    sizes_card_filesize: numeric('sizes_card_filesize', { mode: 'number' }),
    sizes_card_filename: text('sizes_card_filename'),
    sizes_gallery_url: text('sizes_gallery_url'),
    sizes_gallery_width: numeric('sizes_gallery_width', { mode: 'number' }),
    sizes_gallery_height: numeric('sizes_gallery_height', { mode: 'number' }),
    sizes_gallery_mimeType: text('sizes_gallery_mime_type'),
    sizes_gallery_filesize: numeric('sizes_gallery_filesize', { mode: 'number' }),
    sizes_gallery_filename: text('sizes_gallery_filename'),
  },
  (columns) => [
    index('carsgallery_updated_at_idx').on(columns.updatedAt),
    index('carsgallery_created_at_idx').on(columns.createdAt),
    uniqueIndex('carsgallery_filename_idx').on(columns.filename),
    index('carsgallery_sizes_thumbnail_sizes_thumbnail_filename_idx').on(
      columns.sizes_thumbnail_filename,
    ),
    index('carsgallery_sizes_card_sizes_card_filename_idx').on(columns.sizes_card_filename),
    index('carsgallery_sizes_gallery_sizes_gallery_filename_idx').on(
      columns.sizes_gallery_filename,
    ),
  ],
)

export const exports = sqliteTable(
  'exports',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    format: text('format', { enum: ['csv', 'json'] })
      .notNull()
      .default('csv'),
    limit: numeric('limit', { mode: 'number' }),
    page: numeric('page', { mode: 'number' }).default(1),
    sort: text('sort'),
    sortOrder: text('sort_order', { enum: ['asc', 'desc'] }),
    drafts: text('drafts', { enum: ['yes', 'no'] }).default('yes'),
    collectionSlug: text('collection_slug').notNull().default('cars'),
    where: text('where', { mode: 'json' }).default('{}'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('exports_updated_at_idx').on(columns.updatedAt),
    index('exports_created_at_idx').on(columns.createdAt),
    uniqueIndex('exports_filename_idx').on(columns.filename),
  ],
)

export const exports_texts = sqliteTable(
  'exports_texts',
  {
    id: integer('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    text: text('text'),
  },
  (columns) => [
    index('exports_texts_order_parent').on(columns.order, columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [exports.id],
      name: 'exports_texts_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const imports = sqliteTable(
  'imports',
  {
    id: integer('id').primaryKey(),
    collectionSlug: text('collection_slug').notNull().default('cars'),
    importMode: text('import_mode', { enum: ['create', 'update', 'upsert'] }),
    matchField: text('match_field').default('id'),
    status: text('status', { enum: ['pending', 'completed', 'partial', 'failed'] }).default(
      'pending',
    ),
    summary_imported: numeric('summary_imported', { mode: 'number' }),
    summary_updated: numeric('summary_updated', { mode: 'number' }),
    summary_total: numeric('summary_total', { mode: 'number' }),
    summary_issues: numeric('summary_issues', { mode: 'number' }),
    summary_issueDetails: text('summary_issue_details', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text('url'),
    thumbnailURL: text('thumbnail_u_r_l'),
    filename: text('filename'),
    mimeType: text('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('imports_updated_at_idx').on(columns.updatedAt),
    index('imports_created_at_idx').on(columns.createdAt),
    uniqueIndex('imports_filename_idx').on(columns.filename),
  ],
)

export const payload_kv = sqliteTable(
  'payload_kv',
  {
    id: integer('id').primaryKey(),
    key: text('key').notNull(),
    data: text('data', { mode: 'json' }).notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = sqliteTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    executedAt: text('executed_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    completedAt: text('completed_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    taskSlug: text('task_slug', {
      enum: [
        'inline',
        'imageOptimizer_regenerateDocument',
        'createCollectionExport',
        'createCollectionImport',
      ],
    }).notNull(),
    taskID: text('task_i_d').notNull(),
    input: text('input', { mode: 'json' }),
    output: text('output', { mode: 'json' }),
    state: text('state', { enum: ['failed', 'succeeded'] }).notNull(),
    error: text('error', { mode: 'json' }),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = sqliteTable(
  'payload_jobs',
  {
    id: integer('id').primaryKey(),
    input: text('input', { mode: 'json' }),
    completedAt: text('completed_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: integer('has_error', { mode: 'boolean' }).default(false),
    error: text('error', { mode: 'json' }),
    taskSlug: text('task_slug', {
      enum: [
        'inline',
        'imageOptimizer_regenerateDocument',
        'createCollectionExport',
        'createCollectionImport',
      ],
    }),
    queue: text('queue').default('default'),
    waitUntil: text('wait_until').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    processing: integer('processing', { mode: 'boolean' }).default(false),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = sqliteTable(
  'payload_locked_documents',
  {
    id: integer('id').primaryKey(),
    globalSlug: text('global_slug'),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = sqliteTable(
  'payload_locked_documents_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    carsID: integer('cars_id'),
    carBrandsID: integer('car_brands_id'),
    carTypesID: integer('car_types_id'),
    carsgalleryID: integer('carsgallery_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_cars_id_idx').on(columns.carsID),
    index('payload_locked_documents_rels_car_brands_id_idx').on(columns.carBrandsID),
    index('payload_locked_documents_rels_car_types_id_idx').on(columns.carTypesID),
    index('payload_locked_documents_rels_carsgallery_id_idx').on(columns.carsgalleryID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['carsID']],
      foreignColumns: [cars.id],
      name: 'payload_locked_documents_rels_cars_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['carBrandsID']],
      foreignColumns: [car_brands.id],
      name: 'payload_locked_documents_rels_car_brands_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['carTypesID']],
      foreignColumns: [car_types.id],
      name: 'payload_locked_documents_rels_car_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['carsgalleryID']],
      foreignColumns: [carsgallery.id],
      name: 'payload_locked_documents_rels_carsgallery_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = sqliteTable(
  'payload_preferences',
  {
    id: integer('id').primaryKey(),
    key: text('key'),
    value: text('value', { mode: 'json' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = sqliteTable(
  'payload_preferences_rels',
  {
    id: integer('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: text('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = sqliteTable(
  'payload_migrations',
  {
    id: integer('id').primaryKey(),
    name: text('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: text('updated_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at')
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const site = sqliteTable(
  'site',
  {
    id: integer('id').primaryKey(),
    siteName: text('site_name').notNull(),
    domain: text('domain').notNull(),
    logo: integer('logo_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    location: text('location').notNull(),
    address: text('address').notNull(),
    maps: text('maps').notNull(),
    social_whatsapp: text('social_whatsapp').notNull(),
    social_instagram: text('social_instagram').notNull(),
    social_tiktok: text('social_tiktok').notNull(),
    social_facebook: text('social_facebook').notNull(),
    shortDescription: text('short_description').notNull(),
    seo_metaTitle: text('seo_meta_title'),
    seo_metaDescription: text('seo_meta_description'),
    seo_keywords: text('seo_keywords'),
    openGraph_ogTitle: text('open_graph_og_title'),
    openGraph_ogDescription: text('open_graph_og_description'),
    openGraph_ogImage: integer('open_graph_og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    business_city: text('business_city'),
    business_region: text('business_region'),
    business_postalCode: text('business_postal_code'),
    business_latitude: text('business_latitude'),
    business_longitude: text('business_longitude'),
    advancedSEO_canonicalUrl: text('advanced_s_e_o_canonical_url'),
    advancedSEO_robots: text('advanced_s_e_o_robots', { enum: ['index,follow', 'noindex'] }),
    updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index('site_logo_idx').on(columns.logo),
    index('site_open_graph_open_graph_og_image_idx').on(columns.openGraph_ogImage),
  ],
)

export const hero_advantages = sqliteTable(
  'hero_advantages',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    icon: text('icon').notNull(),
  },
  (columns) => [
    index('hero_advantages_order_idx').on(columns._order),
    index('hero_advantages_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [hero.id],
      name: 'hero_advantages_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const hero = sqliteTable(
  'hero',
  {
    id: integer('id').primaryKey(),
    title: text('title').notNull(),
    subTitle: text('sub_title').notNull(),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    whatsappMessage: text('whatsapp_message').notNull(),
    updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [index('hero_background_image_idx').on(columns.backgroundImage)],
)

export const review_reviews = sqliteTable(
  'review_reviews',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    product: text('product').notNull(),
    rating: text('rating', { enum: ['1', '2', '3', '4', '5'] }).notNull(),
    testimoni: text('testimoni').notNull(),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => [
    index('review_reviews_order_idx').on(columns._order),
    index('review_reviews_parent_id_idx').on(columns._parentID),
    index('review_reviews_avatar_idx').on(columns.avatar),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [review.id],
      name: 'review_reviews_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const review = sqliteTable('review', {
  id: integer('id').primaryKey(),
  title: text('title').notNull(),
  subTitle: text('sub_title').notNull(),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
})

export const advantage_advantages = sqliteTable(
  'advantage_advantages',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: text('id').primaryKey(),
    title: text('title').notNull(),
    desc: text('desc').notNull(),
    icon: text('icon').notNull(),
  },
  (columns) => [
    index('advantage_advantages_order_idx').on(columns._order),
    index('advantage_advantages_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [advantage.id],
      name: 'advantage_advantages_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const advantage = sqliteTable('advantage', {
  id: integer('id').primaryKey(),
  title: text('title').notNull(),
  subTitle: text('sub_title').notNull(),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
})

export const image_optimizer_state = sqliteTable('image_optimizer_state', {
  id: integer('id').primaryKey(),
  collections: text('collections', { mode: 'json' }),
  updatedAt: text('updated_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  createdAt: text('created_at').default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_cars_gallery = relations(cars_gallery, ({ one }) => ({
  _parentID: one(cars, {
    fields: [cars_gallery._parentID],
    references: [cars.id],
    relationName: 'gallery',
  }),
  image: one(carsgallery, {
    fields: [cars_gallery.image],
    references: [carsgallery.id],
    relationName: 'image',
  }),
}))
export const relations_cars_features = relations(cars_features, ({ one }) => ({
  _parentID: one(cars, {
    fields: [cars_features._parentID],
    references: [cars.id],
    relationName: 'features',
  }),
}))
export const relations_cars_analytics_repairs = relations(cars_analytics_repairs, ({ one }) => ({
  _parentID: one(cars, {
    fields: [cars_analytics_repairs._parentID],
    references: [cars.id],
    relationName: 'analytics_repairs',
  }),
}))
export const relations_cars_analytics_operational_costs = relations(
  cars_analytics_operational_costs,
  ({ one }) => ({
    _parentID: one(cars, {
      fields: [cars_analytics_operational_costs._parentID],
      references: [cars.id],
      relationName: 'analytics_operationalCosts',
    }),
  }),
)
export const relations_cars_financing_leasing_tenor_months = relations(
  cars_financing_leasing_tenor_months,
  ({ one }) => ({
    parent: one(cars_financing_leasing, {
      fields: [cars_financing_leasing_tenor_months.parent],
      references: [cars_financing_leasing.id],
      relationName: 'tenorMonths',
    }),
  }),
)
export const relations_cars_financing_leasing = relations(
  cars_financing_leasing,
  ({ one, many }) => ({
    _parentID: one(cars, {
      fields: [cars_financing_leasing._parentID],
      references: [cars.id],
      relationName: 'financing_leasing',
    }),
    tenorMonths: many(cars_financing_leasing_tenor_months, {
      relationName: 'tenorMonths',
    }),
  }),
)
export const relations_cars = relations(cars, ({ one, many }) => ({
  carBrand: one(car_brands, {
    fields: [cars.carBrand],
    references: [car_brands.id],
    relationName: 'carBrand',
  }),
  carType: one(car_types, {
    fields: [cars.carType],
    references: [car_types.id],
    relationName: 'carType',
  }),
  cardthumbnail: one(carsgallery, {
    fields: [cars.cardthumbnail],
    references: [carsgallery.id],
    relationName: 'cardthumbnail',
  }),
  gallery: many(cars_gallery, {
    relationName: 'gallery',
  }),
  features: many(cars_features, {
    relationName: 'features',
  }),
  analytics_repairs: many(cars_analytics_repairs, {
    relationName: 'analytics_repairs',
  }),
  analytics_operationalCosts: many(cars_analytics_operational_costs, {
    relationName: 'analytics_operationalCosts',
  }),
  financing_leasing: many(cars_financing_leasing, {
    relationName: 'financing_leasing',
  }),
  meta_image: one(carsgallery, {
    fields: [cars.meta_image],
    references: [carsgallery.id],
    relationName: 'meta_image',
  }),
}))
export const relations_car_brands = relations(car_brands, ({ one }) => ({
  icon: one(media, {
    fields: [car_brands.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_car_types = relations(car_types, ({ one }) => ({
  icon: one(media, {
    fields: [car_types.icon],
    references: [media.id],
    relationName: 'icon',
  }),
}))
export const relations_carsgallery = relations(carsgallery, () => ({}))
export const relations_exports_texts = relations(exports_texts, ({ one }) => ({
  parent: one(exports, {
    fields: [exports_texts.parent],
    references: [exports.id],
    relationName: '_texts',
  }),
}))
export const relations_exports = relations(exports, ({ many }) => ({
  _texts: many(exports_texts, {
    relationName: '_texts',
  }),
}))
export const relations_imports = relations(imports, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    carsID: one(cars, {
      fields: [payload_locked_documents_rels.carsID],
      references: [cars.id],
      relationName: 'cars',
    }),
    carBrandsID: one(car_brands, {
      fields: [payload_locked_documents_rels.carBrandsID],
      references: [car_brands.id],
      relationName: 'carBrands',
    }),
    carTypesID: one(car_types, {
      fields: [payload_locked_documents_rels.carTypesID],
      references: [car_types.id],
      relationName: 'carTypes',
    }),
    carsgalleryID: one(carsgallery, {
      fields: [payload_locked_documents_rels.carsgalleryID],
      references: [carsgallery.id],
      relationName: 'carsgallery',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_site = relations(site, ({ one }) => ({
  logo: one(media, {
    fields: [site.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  openGraph_ogImage: one(media, {
    fields: [site.openGraph_ogImage],
    references: [media.id],
    relationName: 'openGraph_ogImage',
  }),
}))
export const relations_hero_advantages = relations(hero_advantages, ({ one }) => ({
  _parentID: one(hero, {
    fields: [hero_advantages._parentID],
    references: [hero.id],
    relationName: 'advantages',
  }),
}))
export const relations_hero = relations(hero, ({ one, many }) => ({
  backgroundImage: one(media, {
    fields: [hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
  advantages: many(hero_advantages, {
    relationName: 'advantages',
  }),
}))
export const relations_review_reviews = relations(review_reviews, ({ one }) => ({
  _parentID: one(review, {
    fields: [review_reviews._parentID],
    references: [review.id],
    relationName: 'reviews',
  }),
  avatar: one(media, {
    fields: [review_reviews.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
}))
export const relations_review = relations(review, ({ many }) => ({
  reviews: many(review_reviews, {
    relationName: 'reviews',
  }),
}))
export const relations_advantage_advantages = relations(advantage_advantages, ({ one }) => ({
  _parentID: one(advantage, {
    fields: [advantage_advantages._parentID],
    references: [advantage.id],
    relationName: 'advantages',
  }),
}))
export const relations_advantage = relations(advantage, ({ many }) => ({
  advantages: many(advantage_advantages, {
    relationName: 'advantages',
  }),
}))
export const relations_image_optimizer_state = relations(image_optimizer_state, () => ({}))

type DatabaseSchema = {
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  cars_gallery: typeof cars_gallery
  cars_features: typeof cars_features
  cars_analytics_repairs: typeof cars_analytics_repairs
  cars_analytics_operational_costs: typeof cars_analytics_operational_costs
  cars_financing_leasing_tenor_months: typeof cars_financing_leasing_tenor_months
  cars_financing_leasing: typeof cars_financing_leasing
  cars: typeof cars
  car_brands: typeof car_brands
  car_types: typeof car_types
  carsgallery: typeof carsgallery
  exports: typeof exports
  exports_texts: typeof exports_texts
  imports: typeof imports
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  site: typeof site
  hero_advantages: typeof hero_advantages
  hero: typeof hero
  review_reviews: typeof review_reviews
  review: typeof review
  advantage_advantages: typeof advantage_advantages
  advantage: typeof advantage
  image_optimizer_state: typeof image_optimizer_state
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_cars_gallery: typeof relations_cars_gallery
  relations_cars_features: typeof relations_cars_features
  relations_cars_analytics_repairs: typeof relations_cars_analytics_repairs
  relations_cars_analytics_operational_costs: typeof relations_cars_analytics_operational_costs
  relations_cars_financing_leasing_tenor_months: typeof relations_cars_financing_leasing_tenor_months
  relations_cars_financing_leasing: typeof relations_cars_financing_leasing
  relations_cars: typeof relations_cars
  relations_car_brands: typeof relations_car_brands
  relations_car_types: typeof relations_car_types
  relations_carsgallery: typeof relations_carsgallery
  relations_exports_texts: typeof relations_exports_texts
  relations_exports: typeof relations_exports
  relations_imports: typeof relations_imports
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_site: typeof relations_site
  relations_hero_advantages: typeof relations_hero_advantages
  relations_hero: typeof relations_hero
  relations_review_reviews: typeof relations_review_reviews
  relations_review: typeof relations_review
  relations_advantage_advantages: typeof relations_advantage_advantages
  relations_advantage: typeof relations_advantage
  relations_image_optimizer_state: typeof relations_image_optimizer_state
}

declare module '@payloadcms/db-sqlite' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
