name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Compress Project
        run: |
          tar \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=db \
            --exclude=.next \
            --exclude=deploy.tar.gz \
            -czf deploy.tar.gz \
            .

      - name: Upload Project
        run: |
          scp -i ~/.ssh/id_ed25519 \
            -P ${{ secrets.SERVER_PORT }} \
            deploy.tar.gz \
            root@${{ secrets.SERVER_HOST }}:/root/apps/

      - name: Extract & Build on Server
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.SERVER_PORT }} \
            root@${{ secrets.SERVER_HOST }} << 'EOF'
            mkdir -p /root/apps/mawarmotor-web
            cd /root/apps/mawarmotor-web
            
            # Hapus file lama (kecuali database .db dan file .env)
            rm -rf .next public src package.json package-lock.json next.config.ts tsconfig.json postcss.config.mjs components.json eslint.config.mjs
            
            # Ekstrak source code baru
            tar -xzf ../deploy.tar.gz
            
            # Install dependensi & build langsung di server
            npm install
            npm run build
            
            # Restart PM2
            pm2 restart mawar-motor-app || pm2 start npm --name "mawar-motor-app" -- start
            pm2 save
          EOF