name: Deploy VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Create Environment
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

          mkdir -p db

          touch db/database.db

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519

          chmod 600 ~/.ssh/id_ed25519

          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Compress Project
        run: |
          tar \
            --exclude=node_modules \
            --exclude=.git \
            --exclude=db \
            -czf deploy.tar.gz \
            .next \
            public \
            src \
            package.json \
            package-lock.json \
            next.config.ts \
            .env

      - name: Upload Project
        run: |
          scp -i ~/.ssh/id_ed25519 \
            -P ${{ secrets.SERVER_PORT }} \
            deploy.tar.gz \
            root@${{ secrets.SERVER_HOST }}:/root/apps/

      - name: Extract & Restart
        run: |
          ssh -i ~/.ssh/id_ed25519 \
            -p ${{ secrets.SERVER_PORT }} \
            root@${{ secrets.SERVER_HOST }} << 'EOF'
            mkdir -p /root/apps/mawarmotor-web
            cd /root/apps/mawarmotor-web
            rm -rf .next
            rm -rf public
            rm -rf src
            tar -xzf ../deploy.tar.gz
            npm install --omit=dev
            pm2 restart mawar-motor-app || pm2 start npm --name "mawar-motor-app" -- start
            pm2 save
          EOF